# VLMJudge on PASTA test set (requires VLM server)
explain:
  method: VLMJudge
  saliency:
    method: CAMSaliency
    cam: GradCAM
    layer: 0
    slope: 25
    position: 0.4
  kwargs:
    cam_mode: masked
    threshold: 2.5
  vlm:
    client: VLLMClient
    kwargs:
      model_name: Qwen/Qwen3-VL-2B-Instruct
      port: 8000

datasets:
  - name: pasta_test_VLMJudge
    path: /home/phng1216/Thesis/PASTA/PASTA/test_imgs
    model:
      source: torchvision
      name: resnet18
      model_type: classification
      weight: DEFAULT

output: /home/phng1216/Thesis/autoXplain/outputs
