## CAMSaliency (GradCAM) on COCO mini-train-10k

explain:
  name: CAMSaliency
  kwargs:
    cam: GradCAM
    layer: 0
    slope: 25
    position: 0.4

datasets:
  - name: ImageProcess
    ds_name: coco_CAM_GradCAM
    path: /home/phng1216/Thesis/autoXplain/datasets/annotated/coco/coco_minitrain_10k/images/test
    model:
      name: torchvision

output: /home/phng1216/Thesis/autoXplain/outputs/coco
